###################
### CONFIG VARS ###
###################
# RBENV
rbenv_root: /usr/local/rbenv
ruby_version: 2.2.6

#NGINX
config_file_path: files/nginx.conf

#DB SETUP
db_name: sinatra_api_db
db_user: sinatra_developer
db_user_password: developer