GET http://eventomate.dev:8080/api/users/
content-type: application/json

###
GET http://eventomate.dev:8080/api/users/1/account
content-type: application/json

###
PUT http://eventomate.dev:8080/api/accounts/1
Content-Type: application/json

{
	"name": "Simun Strukan",
	"email": "simun.strukan@gmail.com"
}

###
POST http://eventomate.dev:8080/api/authenticate/change/password
Content-Type: application/json

{
	"email": "simun.strukan@gmail.com",
	"password": "0077ss",
	"new_password": "an00biis"
}